base/urls.py
from django.urls import path
from . import views
urlpatterns =[
    path('',views.home,name="home"),
    path('login/',views.loginPage,name="login"),
    path('register/',views.registerPage,name="register"),
  
    path('complaint/',views.complaint,name="complaint"),
    path('empdashboard/',views.empdashboard,name="empdash"),
    path('empcategory/',views.empcategory,name="empcat"),
    path('empallcomp/',views.empallcomp,name="empallcomp"),
    path('assign/<str:pk>',views.assignment,name="assign"),
    path('comment/<str:pk>',views.comment,name="comment"),
    path('userdash/',views.userdashboard,name="userdash"),
    path('usercomplaint/',views.usercreatecomp,name="usercomp"),
    path('usercompstatus/',views.usercompstatus,name="usercompstatus"),
    path('userprofile/',views.userprofile,name="userprofile"),
    path('table',views.table,name="table"),
    
    path('progress/<str:pk>',views.progress,name="progress"),
   
    path('support/',views.support,name="support"),
    path('privacy/',views.privacy,name="privacy"),
    path('about/',views.about,name="about"),
    path('tandc/',views.tandc,name="tandc"),
    path('emppending/',views.emppending,name="emppending"),


]

neelAayush/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from base import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    # path(r'*download/(?P<path>.*)$', serve,{'download_root':settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):

    is_user = models.BooleanField('Is user',default=False)
    is_employee = models.BooleanField('Is employee',default=False)
    is_admin = models.BooleanField('Is admin',default=False)
    
    # def __str__(self):
    #     return self.name

class Complaint(models.Model):
    ticketid = models.CharField(primary_key=True,max_length=20)
    complainant = models.ForeignKey(User, on_delete = models.SET_NULL,null=True)
    type = models.CharField(max_length=50)
    subject = models.CharField(max_length=100)
    desc = models.CharField(max_length=1000)
    docLink = models.CharField(max_length=1000)
    handler = models.CharField(max_length=30)
    status = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.ticketid

class Comment(models.Model):
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    ticketid = models.ForeignKey(Complaint,on_delete=models.CASCADE)
    body = models.TextField(max_length=400,null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated','-created']


class ProgressBar(models.Model):
    commentee = models.ForeignKey(User, on_delete=models.CASCADE)
    tid = models.ForeignKey(Complaint,on_delete=models.CASCADE)
    bar = models.TextField(max_length=3,null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

base/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User,Complaint

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = ( 'username','email', 'password1', 'password2')

class CompForm(ModelForm):
    class Meta:
        model = Complaint
        #Includes all the attributes from the Room model
        fields ='__all__' 
        exclude=['ticketid','complainant','handler','status','created']

base/views.py
import random
import string
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from base.models import User,Complaint,Comment, ProgressBar
from django.contrib import messages
from .forms import SignUpForm, LoginForm, CompForm
from django.core import serializers

# Create your views here.
def home(request):
    return render(request,'base/home.html')

def loginPage(request):
    page = 'login'
    form = LoginForm(request.POST or None)
    messages = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # print(username)
            # print(password)
            try:
                user = User.objects.get(username=username)
                employee1 = User.objects.get(username=username)
            except:
                return None
            print(user)
            authh = authenticate(username=username, password=password)
            
            if user is not None and user.is_user:
                login(request, user)
                return redirect('userdash')
            elif user is not None and user.is_employee:
                login(request, user)
                return redirect('empdash')
            elif user is not None and user.is_admin:
                login(request, user)
                return redirect('admincomp')
            elif user is not None and (user.is_user == False & user.is_employee == False & user.is_admin == False):
                login(request, user)
                return redirect('userdash')
            else:
                messages= 'invalid credentials'
        else:
            messages = 'error validating form'
    return render(request,'base/reg_form.html', {'form': form, 'messages': messages,'page':page})

def registerPage(request):
    # messages = ''
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(user)
            user.save()
            print(user)
            # messages.info(request, 'User created')
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')
    else:
        form = SignUpForm()
    return render(request,'base/reg_form.html', {'form': form, 'messages': messages})

def logoutUser(request):
    logout(request)
    return redirect('home')

@login_required(login_url='login')
def complaint(request):
    form = CompForm()
    comp = Complaint.objects.all()
    tid=pwd()
    if request.method =='POST':
        Complaint.objects.create(
        ticketid=tid,
        complainant=request.user,
        type=request.POST.get("type"),
        subject = request.POST.get('subject'),
        desc = request.POST.get('desc'),
        docLink = request.POST.get('link'),
        )
    return render(request,'base/complaint.html')
def table(request):
    return render(request,'base/table.html')
    
def pwd():
    dummy_str = ''.join((random.choice(string.ascii_letters) for i in range(2)))
    dummy_str+=''.join((random.choice(string.digits) for i in range(3)))
    dummy_list=list(dummy_str)
    final_pwd=''.join(dummy_list)
    return final_pwd

#EMAIL AUTHENTICATION
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

def empdashboard(request):
    comp=Complaint.objects.all()
    count=comp.count()
    cnt=0
    for i in comp:
        if i.status == '':
            cnt=cnt+1
    
    return render(request,'base/empdash.html',{'count':count,'cnt':cnt})
def empcategory(request):
    return render(request,'base/empcategory.html')
def empallcomp(request):
    # data = serializers.serialize("python",Complaint.objects.all())
    comp = Complaint.objects.all()

    # tid=comp.ticketid()
   
    return render(request,'base/empallcomp.html',{'comp':comp})

def assignment(request,pk):
    comp = Complaint.objects.get(ticketid=pk) #SEND ticketid for checking
    comp.handler = str(request.user)
    comp.status = "In-Progress"
    comp.save()
    return render(request,'base/extra.html')

def escalate(request,pk):
    comp=Complaint.objects.get(ticketid=pk)
    tid=comp.ticketid
    cmpt=comp.complainant
    ty=comp.type
    sub=comp.subject
    ds=comp.desc
    link=comp.docLink
    hdlr=comp.handler
    sts=comp.status
    
    return render(request,'base/escalate.html')
    
def comment(request,pk):
    compp = Complaint.objects.all()
    comp = Complaint.objects.get(ticketid=pk)
    # cc = comp.comment_set.all()

    if request.method == 'POST':
        Comment.objects.create(
                commenter=request.user,
                ticketid = comp,
                body = request.POST.get('body'),
        )

        return redirect('comment', pk=comp.ticketid)
    return render(request,'base/comment.html',{'comp':comp})

def progress(request,pk):
    compp=Complaint.objects.get(ticketid=pk)
    if request.method =='POST':
        ProgressBar.objects.create(
            commentee=request.user,
            tid = compp,
            bar=request.POST.get('barbody'),

        )
        return redirect('comment',pk=compp.ticketid)
    return render(request,'base/comment.html')


def userdashboard(request):
    comp=Complaint.objects.all()
    return render(request,'base/userdash.html',{'comp':comp}) 
def usercreatecomp(request):
    return render(request,'base/usercomp.html')

# *********************


def usercompstatus(request):
    bar=ProgressBar.objects.all()
    comp=Complaint.objects.all()
    
    return render(request, 'base/usercompstatus.html',{'comp':comp,'bar':bar})

# ****************************

def userprofile(request):
    return render(request,'base/userprofile.html')

# def status(request,pk):
#     comp=Complaint.objects.get(ticketid=pk)
#     return render(request,'base/status.html',{'comp':comp})

# def adminallcomp(request):
#     comp = AdminComp.objects.all()
#     return render(request,'base/adminallcomp.html',{'comp':comp})
# def fileUpload(request,pk):
#     comp = Complaint.objects.get(ticketid=pk)

#     return None

# def docSub(request,pk):
#     comp = Complaint.objects.get(ticketid=pk)
#     context={}
#     if comp.docs != None:
#         context={'file':comp.docs}
#     return render(request, 'base/complaint.html',context)
# def regComp(request)

def about(request):
    return render(request,'base/about.html')
def tandc(request):
    return render(request,'base/tandc.html')
# 
def support(request):
    return render(request,'base/support.html')
def privacy(request):
    return render(request,'base/privacy.html')

def emppending(request):
    comp=Complaint.objects.all()
   
    return render(request,'base/emppending.html',{'comp':comp})

base/templates/base/about.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>About Us</title>
  <link href="{% static 'styles/styles.css' %}" rel="stylesheet" type="text/css"/>
   <link href="{% static 'styles/tandc.css' %}" rel="stylesheet" type="text/css"/>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/logo.png' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="about">
<div class="navbar">
  <a href="{% url 'home' %}"><img src="{% static 'images/logo.png'%}"></a>
  <div class="nav-right">
  <a href="{% url 'tandc' %}" target="_blank">T&C</a>
  <a href="{% url 'support' %}" target="_blank">FAQ's</a>
  <a href="{% url 'complaint' %}" target="_blank"><i class="fa fa-address-book-o" aria-hidden="true"></i></a>
  </div>
</div>
<div class="topic">
  <h1>About <span style="color: #8EFF84;">Us</span></h1>
  <hr>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At viverra lacus vitae a molestie turpis. Amet neque turpis sit nunc, ut varius praesent fermentum vel. Tincidunt ac duis ultricies nisi nam enim, dictum. Eget nunc, sagittis sagittis vulputate nunc hendrerit augue suscipit neque. Nullam eget et, rhoncus vehicula purus dictum.</p> 

<p>Euismod tristique amet, fringilla nunc, elit. Quam vitae at blandit lacus blandit scelerisque. Sed vulputate turpis a, nunc, nullam malesuada. Dolor mi aliquet sed pharetra ullamcorper. Enim erat venenatis amet consectetur amet, vel viverra quam turpis.</p> 

<p>>Dignissim rhoncus turpis ut in. Platea volutpat lorem ultricies vulputate. Urna gravida quis turpis pulvinar amet, rhoncus. Tortor amet in scelerisque vitae pellentesque felis</p>

<p>Nunc vel id tortor eget sit. Ut donec consequat aliquam odio quam sem amet rhoncus risus. Dignissim tortor tempor mattis augue nulla orci tortor elit. In eget vel pellentesque dictum sem ut sapien, aliquet. Consectetur mattis faucibus eleifend mi placerat. </p>

<p>Consequat nibh diam tempus vel nec varius libero suspendisse elementum. In platea sit velit turpis magnis nam mi. Etiam nulla sed porta turpis ut aliquam quis. Tristique vitae, posuere varius sit vulputate aliquet et. Faucibus enim justo mattis id nec. Nec mi nulla nunc, gravida vestibulum quam tellus sapien erat.</p>

<p>Eleifend rutrum eleifend ultricies egestas interdum. Sollicitudin habitant mauris, mattis a, placerat venenatis, varius. Habitant risus, eu sed ac. Sagittis lacus in libero ornare viverra diam. </p>

<p>Adipiscing mollis dignissim aliquam, pellentesque eu. Praesent proin ultricies in sit amet tellus in duis mollis. Odio scelerisque condimentum quis condimentum velit, vel eget enim tellus. Enim libero sagittis consectetur a venenatis enim gravida. Tristique quam porttitor mollis interdum sit maecenas cras nam quisque. </p>

<p>m, semper libero et aliquam. Nunc dignissim at tempus purus magna in duis placerat lacus.
Placerat purus tristique elit et lacus non at vestibulum. Turpis.</p>
  <a href="#" target="_blank"><button>File a complaint</button></a>
</div>
  <hr>
<div class="tc">
  <h2>Terms and Condition</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis morbi vel, porta nisl, molestie est. Phasellus adipiscing lobortis amet egestas eget diam leo. Duis quis cursus at dui enim proin at scelerisque diam.</p>
</div>
<footer>
  <a href="{% url 'support' %}" target="_blank">Support</a>
  <a>© 2022 AAYUSH All rights reserved</a>
  <a href="privacy.html" target="_blank">Privacy Policy</a>
</footer>
</body>
</html>

base/templates/base/adminallcomp.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <title>Neel Aayush</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
  <link rel='stylesheet' href='https://morrisjs.github.io/morris.js/css/morris.css'>
  <link rel="stylesheet" href="{% static 'styles/emp.css' %}">

</head>

<body>
  <!-- partial:index.partial.html -->

  <body>
    <div class="">
      <header class="navbar-fixed-top">
        <div class="row">
          <div class="container-fluid" style="background-color: white;">
            <div class="pull-left">
              <div class="pull-left logo text-center">
                <!-- <span><img src="{% static 'images/logo.png' %}" style="width: 200px;"></img></span> -->
              </div>
              <!--             <button class="btn btn-primary menu"><span class=
            "glyphicon glyphicon glyphicon-menu-hamburger"></span></button> -->
            </div>
            <div class="pull-right">
              <div class="marr20">
                <ul class="nav navbar-top-links navbar-right">
                  <li class="dropdown task"></li><!-- /.dropdown -->
                  <li class="dropdown bell">
                    <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#"><i
                        class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-alerts">
                      <li>
                        <a href="#">
                          <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment <span class="pull-right text-muted small">4
                              minutes ago</span>
                          </div>
                        </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="#">
                          <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers <span
                              class="pull-right text-muted small">12 minutes ago</span>
                          </div>
                        </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="#">
                          <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent <span
                              class="pull-right text-muted small">4
                              minutes ago</span>
                          </div>
                        </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="#">
                          <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task <span class="pull-right text-muted small">4
                              minutes
                              ago</span>
                          </div>
                        </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="#">
                          <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted <span
                              class="pull-right text-muted small">4
                              minutes ago</span>
                          </div>
                        </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a class="text-center" href="#"><strong>See All Alerts</strong> <i
                            class="fa fa-angle-right"></i></a>
                      </li>
                    </ul><!-- /.dropdown-alerts -->
                  </li><!-- /.dropdown -->
                  <li class="dropdown user">
                    <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#"><i
                        class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-user">
                      <li>
                        <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                      </li>
                      <li>
                        <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="{% url 'login' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                      </li>
                    </ul><!-- /.dropdown-user -->
                  </li><!-- /.dropdown -->
                </ul>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div class="wrap">
        <div class="side-menu" style="background-color: white;">
          <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
              <div class="brand-wrapper">
  <!--               <div class="brand-name-wrapper">
                  
  <!--               </div><a class="btn btn-default" data-toggle="collapse" href="#search" id="search-trigger"><span class=
                "glyphicon glyphicon-search"></span></a>
                <div class="panel-collapse collapse" id="search"> -->
  <!--                 <div class="panel-body">
                    <form class="navbar-form" role="search">
                      <div class="form-group">
                        <input class="form-control" placeholder="Search" type="text">
                      </div><button class="btn btn-default" type="submit"><span class=
                      "glyphicon glyphicon-ok"></span></button>
                    </form>
                  </div>
                </div> --> 
              </div>
            </div><!-- Main Menu -->
            <div class="side-menu-container">
              <ul class="nav navbar-nav" style="background-color:white">
                <li>
                  <a href="{% url 'empdash' %}"><span class="glyphicon glyphicon-send"></span> Dashboard</a>
                </li>
                <li class="active">
                  <a href="{% url 'empcat' %}"><span class="glyphicon glyphicon-plane"></span> Categories</a>
                </li>
                <!-- <li>
                  <a href="#"><span class="glyphicon glyphicon-cloud"></span> Categories </a>
                </li> -->
                <li>
                  <a href="#"><span class="glyphicon glyphicon-cloud"></span> Report </a>
                </li><!-- Dropdown-->
                <li class="panel panel-default" id="dropdown">
                  <a data-toggle="collapse" href="#dropdown-lvl1"><span class="glyphicon glyphicon-user"></span> Complaints <span class="caret"></span></a> <!-- Dropdown level 1 -->
                  <div class="panel-collapse collapse" id="dropdown-lvl1">
                    <div class="panel-body">
                      <ul class="nav navbar-nav">
                        <li>
                          <a href="{% url 'empallcomp' %}">All complaints</a>
                        </li>
                        <li>
                          <a href="#">Pending complaints</a>
                        </li>
                        <li>
                          <a href="#">Closed complaints</a>
                        </li>
                        <!-- Dropdown level 2 -->
                        
                      </ul>
                    </div>
                  </div>
                </li>
                <li>
                 
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </nav>
      </div><!-- Main Content -->
      <div class="container-fluid">
        <div class="side-body">
          <div class="page-title-box">
            <h3 class="page-title pull-left">Complaint history</h3>
            <ol class="breadcrumb pull-right">
              <li>
                <!--                 <a href="#">home</a>
              </li> -->
                <!--               <li class="active">Dashboard</li> -->
            </ol>
            <div class="clearfix"></div>
          </div>

          <div class="container">
            <table>
              <thead>
                <tr>
                  <th>Ticket ID</th>
                  <th>Complainant</th>
                  <th>Type</th>
                  <th>Description</th>
                  <th>Document link</th>
                  <th>Status</th>
                  <th>Assignment</th>
                  <th>Handler</th>
                </tr>
              </thead>
              <tbody>
                {% for data in comp %}
                <tr>
                  <td><a href="{% url 'comment' data.ticketid %}" style="cursor:pointer">{{data.ticketid}}</a></td>
                  <td>{{data.complainant}}</td>
                  <td>{{data.type}}</td>
                  <td>{{data.desc}}</td>
                  <td><a style="cursor:pointer">{{data.docLink}}</a></td>
                  <td>{{data.status}}</td>
                  {% if data.handler == '' %}
                  <td><a href="{% url 'assign' data.ticketid %}" style="cursor:pointer">Assign me</a></td>
                  {% else %}
                  <td>Open</td>
                  {% endif %}
                  <td>{{data.handler}}</td>
                </tr>

                
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="row">
            <div class="col-lg-10 col-sm-10">
              <div class="row">
                <!--                 <div class="col-sm-6"> -->
                <!--                 <div class="panel panel-primary"> -->
                <div class="panel-heading">
                  <div class="row">
                    <div class="col-xs-9">
                      <div class="huge">
                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>

  </body>
  <!-- partial -->
  <script src='https://code.jquery.com/jquery-1.12.4.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js'></script>
  <script src='https://cdn.oesmith.co.uk/morris-0.4.1.min.js'></script>
  <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
  <script src="./script.js"></script>

</body>

</html>

base/templates/base/escalate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    The complaint #1234 has been escalated
</body>
</html>

base/templates/base/reg_form.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>User Login/ Signup</title>
  
  <link href="{% static 'styles/loginn.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'styles/styles.css' %}" rel="stylesheet" type="text/css"/>
  <link rel="shortcut icon" type="image/x-icon" href="assets/logo.png">
 
    <style>
      .front_card {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        width: 600px;
        height: 650px;
        background-image: linear-gradient(135deg, #f5f7fa 10%, #c3cfe2 100%);
        display: flex;
      
        clip-path: polygon(0 0, 50% 0, 50% 100%, 0 100%);
        /*clip-path: polygon(50% 0, 100% 0, 100% 100%, 50% 100%);*/
        transition: clip-path 0.5s ease;
      }
      
        <!-- #id_is_user{
        position: relative;
        left:-25px;
        }
        #id_is_employee{
            position: relative;
            left:-2px;
        }
        #id_is_admin{
                position: relative;
                left:-17px;
            } -->
        #labels{
            position: relative;
           
            right:-10px;
    }
    .form-control{
    padding:4px 4px 4px 4px;
    }
        

        </style>
</head>
<body>
  <div class="container">
    <div class="front_card">
      
        <form action="#" class="login_form" method="POST">
          <h1>Login</h1>
          {% csrf_token %}
          <label for="username">Username</label>
          {{ form.username }}      
          <label for="password">Password</label>
          {{ form.password }}
          <a href="#"><p><u>Forgot password?</u></p></a>
          <button class="login_btn">
            Login</button>
            
        </form>
       
        <form action="{% url 'login' %}" class="signup_form" method="POST">
            {% csrf_token %}
          <h1>Signup</h1>
          <label for="username">Username</label>
          {{ form.username }}
          <label for="email">Email</label>
          {{ form.email}}
          <label for="password">Password</label>
          {{ form.password1 }}
          <label for="password">Password</label>
          {{ form.password2 }}
          
            
          <button class="login_btn">Signup</button>
        </form>
      </div>
      <div class="back_card">
        <div class="login_msg">
          <p>Already have an account?</p>
          <button action="{% url 'login' %}" class="login_msg_btn">
            Log-in</button>
        </div>
        <div class="signup_msg">
          <p>Don't have an account?</p>
          <button class="signup_msg_btn">Sign-up</button>
        </div>
      </div>
    </div>


  <script>
    const frontCard = document.querySelector(".front_card");
const signUpBtn = document.querySelector(".signup_msg_btn");
const loginBtn = document.querySelector(".login_msg_btn");
const userEmailInp = document.querySelector(".user_email");
const userFNameInp = document.querySelector(".user_full_name");

signUpBtn.addEventListener("click", () => {
  frontCard.classList.add("front_card_signup");
  userFNameInp.focus();
});

loginBtn.addEventListener("click", () => {
  frontCard.classList.remove("front_card_signup");
  userEmailInp.focus();
});
  </script>
</body>
</html>

base/templates/base/status.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Neel Aayush</title>
    <button> <a href="{% url 'usercompstatus' comp.ticketid %}"></a>
        Check status</button>
</head>
<body>
    
</body>
</html> -->